server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /music/

spring:
  application:
    name: woodwhales-music
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  profiles:
    active: '@profiles.active@'


